# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Doing the blog thing
email: ciro.iriarte+blog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  These are personal notes I believe would like to recall at some point in time,
  sharing them to the wind...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iriarte.it" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ciroiriarte
github_username:  ciroiriarte
twitter:
  username: ciroiriarte
  card: summary
google_site_verification: wLRgHwF6nai9tTLgxgfnssURwBRLZG68NZtpiEPMN94
#google_search_console:
#  verification_file_code: bb8c66e6541c937c
#google_analytics: G-THPGTGRM0T
#google_analytics: G-TF5EZYNCJ4
#google_analytics: 405861805


# Build settings
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compose
  - jekyll-remote-theme
#  - jekyll-google_search_console_verification_file


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

languages: ["en", "es"]
timezone: America/Asuncion

jekyll_admin:
  #hidden_links:
  #  - posts
  #  - pages
  #  - staticfiles
  #  - datafiles
  #  - configuration
  homepage: "posts"

jekyll_compose:
  post_default_front_matter:
    last_modified_at: 
    permalink: 
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags: